export {default as Header} from './Header/Header'
export {default as Slider} from './Slider/Slider'
export {default as Primary} from './Primary/Primary'
export {default as About} from './About/About'
export {default as News} from './News/News'
export {default as Footer} from './Footer/Footer'
export {default as Map} from './Map/Map'